  version: "3"
  tasks:
      generate:
        aliases:
          - gen
        desc: "Generate code from proto files"
        cmd:
          - protoc -I proto proto/gRPC-S/gRPC-S.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative